/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\theme\vela.ts
 * Command: astryx theme build src\theme\vela.ts
 * Generated: 2026-07-27T19:20:36.860Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
