/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\theme\vela.ts
 * Command: astryx theme build src\theme\vela.ts
 * Generated: 2026-07-27T19:20:36.861Z
 */

/// <reference path="./vela.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const velaTheme: DefinedTheme;
